"""SASTbench HTML report generator.

Generates a simple shareable HTML report from benchmark results JSON.

Usage:
    python scripts/report.py results.json
    python scripts/report.py results.json --output report.html
"""

import argparse
import json
import sys
from pathlib import Path


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>SASTbench Report — {scanner_name}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; color: #1a1a1a; }}
  h1 {{ border-bottom: 2px solid #333; padding-bottom: 0.5rem; }}
  .meta {{ color: #666; font-size: 0.9rem; margin-bottom: 2rem; }}
  .summary {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 1rem; margin: 1.5rem 0; }}
  .metric {{ background: #f5f5f5; border-radius: 8px; padding: 1rem; text-align: center; }}
  .metric .value {{ font-size: 2rem; font-weight: bold; }}
  .metric .label {{ font-size: 0.85rem; color: #666; margin-top: 0.25rem; }}
  .agentic {{ background: #e8f5e9; }}
  table {{ width: 100%; border-collapse: collapse; margin: 1.5rem 0; }}
  th, td {{ padding: 0.5rem 0.75rem; text-align: left; border-bottom: 1px solid #ddd; }}
  th {{ background: #f5f5f5; font-weight: 600; }}
  .tp {{ color: #2e7d32; }}
  .fn {{ color: #c62828; }}
  .cap-fp {{ color: #e65100; }}
  .fp {{ color: #f57f17; }}
  footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #ddd; color: #999; font-size: 0.8rem; }}
</style>
</head>
<body>
<h1>SASTbench Report</h1>
<div class="meta">
  <strong>Scanner:</strong> {scanner_name} v{scanner_version} &nbsp;|&nbsp;
  <strong>Track:</strong> {track} &nbsp;|&nbsp;
  <strong>Benchmark:</strong> v{benchmark_version} &nbsp;|&nbsp;
  <strong>Date:</strong> {timestamp}
</div>

<h2>Summary Metrics</h2>
<div class="summary">
  <div class="metric agentic">
    <div class="value">{agentic_score}</div>
    <div class="label">Agentic Score</div>
  </div>
  <div class="metric">
    <div class="value">{recall}</div>
    <div class="label">Recall</div>
  </div>
  <div class="metric">
    <div class="value">{precision}</div>
    <div class="label">Precision</div>
  </div>
  <div class="metric">
    <div class="value">{capability_fp_rate}</div>
    <div class="label">Capability FP Rate</div>
  </div>
  <div class="metric">
    <div class="value">{mixed_intent_accuracy}</div>
    <div class="label">Mixed-Intent Accuracy</div>
  </div>
</div>

<h2>Per-Case Results</h2>
<table>
  <thead>
    <tr>
      <th>Case ID</th>
      <th>Findings</th>
      <th class="tp">TP</th>
      <th class="fn">FN</th>
      <th class="fp">FP</th>
      <th class="cap-fp">Cap FP</th>
    </tr>
  </thead>
  <tbody>
    {case_rows}
  </tbody>
</table>

<footer>
  Generated by SASTbench v{benchmark_version} &mdash;
  <em>Can your scanner find real vulnerabilities in agentic repos
  without flagging the code the agent is supposed to run?</em>
</footer>
</body>
</html>
"""


def format_pct(value: float) -> str:
    return f"{value:.1%}"


def generate_report(results: dict) -> str:
    """Generate HTML report from results JSON."""
    summary = results["summary"]
    scanner = results["scanner"]

    case_rows = []
    for cr in results["caseResults"]:
        s = cr["scoring"]
        row = (
            f"    <tr>"
            f"<td>{cr['caseId']}</td>"
            f"<td>{len(cr['findings'])}</td>"
            f"<td class='tp'>{s['truePositives']}</td>"
            f"<td class='fn'>{s['falseNegatives']}</td>"
            f"<td class='fp'>{s['falsePositives']}</td>"
            f"<td class='cap-fp'>{s['capabilityFalsePositives']}</td>"
            f"</tr>"
        )
        case_rows.append(row)

    html = HTML_TEMPLATE.format(
        scanner_name=scanner["name"],
        scanner_version=scanner["version"],
        track=results["track"],
        benchmark_version=results["benchmarkVersion"],
        timestamp=results["timestamp"][:10],
        agentic_score=format_pct(summary["agenticScore"]),
        recall=format_pct(summary["recall"]),
        precision=format_pct(summary["precision"]),
        capability_fp_rate=format_pct(summary["capabilityFpRate"]),
        mixed_intent_accuracy=format_pct(summary["mixedIntentAccuracy"]),
        case_rows="\n".join(case_rows),
    )

    return html


def main() -> int:
    parser = argparse.ArgumentParser(description="SASTbench HTML report generator")
    parser.add_argument("results", type=Path, help="Results JSON file")
    parser.add_argument("--output", "-o", type=Path, help="Output HTML file")
    args = parser.parse_args()

    if not args.results.exists():
        print(f"Results file not found: {args.results}")
        return 1

    with open(args.results) as f:
        results = json.load(f)

    html = generate_report(results)

    output = args.output or args.results.with_suffix(".html")
    with open(output, "w") as f:
        f.write(html)

    print(f"Report written to {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
